version: "3.8"

services:
    frontend_vite:
        container_name: frontend_vite
        hostname: frontend_vite
        restart: unless-stopped
        build:
            context: ..
            dockerfile: docker/Dockerfile.frontend
        ports:
            - "443:443"
        networks:
            - internal

networks:
    internal:
        driver: bridge
